# Generated by Django 5.0.1 on 2024-04-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0003_remove_connection_connections_connection_user_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
            ],
        ),
    ]
